# Generated by Django 5.0.1 on 2024-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('ID_Escola', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=150)),
                ('Agrupamento', models.CharField(max_length=150)),
                ('Localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
