# Generated by Django 5.0.1 on 2024-01-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ID_Aluno', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('ID_Curso', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('ID_Escola', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=150)),
                ('Agrupamento', models.CharField(max_length=150)),
                ('Localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('ID_Falta', models.BigAutoField(primary_key=True, serialize=False)),
                ('ID_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('ID_Horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fim', models.TimeField()),
                ('Dia_semana', models.CharField(max_length=100)),
                ('Disciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ID_Professor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('ID_Escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('ID_Sala', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome_Sala', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('ID_Turma', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Numero_Alunos', models.IntegerField()),
                ('ID_Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.curso')),
                ('ID_Escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.escola')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='falta',
            name='ID_Horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.horario'),
        ),
        migrations.AddField(
            model_name='horario',
            name='ID_Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.professor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='ID_Sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.sala'),
        ),
        migrations.AddField(
            model_name='horario',
            name='ID_Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ID_Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.turma'),
        ),
    ]
